import AuthComponent from "@/components/AuthComponent";
import AuthProvider from "@/components/AuthProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next JS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0e0e0f]`}
      >
        <AuthProvider>
          <header className="w-full border-b border-[#242427] bg-[#151517] py-4 shadow-sm mb-5">
            <div className="mx-auto flex max-w-5xl items-center justify-between px-4">
              <h1 className="text-xl font-semibold text-[#fafafa]">My App</h1>
              <nav className="flex gap-4">
                <a href="/" className="text-[#fafafa] hover:text-gray-600">
                  Home
                </a>
                <a href="/about" className="text-[#fafafa] hover:text-gray-600">
                  About
                </a>
                <a
                  href="/contact"
                  className="text-[#fafafa] hover:text-gray-600"
                >
                  Contact
                </a>
                <a href="/blog" className="text-[#fafafa] hover:text-gray-600">
                  Blog
                </a>
          <AuthComponent />
              </nav>
            </div>
          </header>

          <main className="min-h-screen w-full px-4 py-6 mx-auto max-w-5xl">
            {children}
          </main>

          <footer className="w-full border-t border-[#242427] bg-[#151517] py-4 mt-10">
            <div className="mx-auto max-w-5xl px-4 text-center text-sm text-[#fafafa]">
              © 2025 My App. All rights reserved.
            </div>
          </footer>
        </AuthProvider>
      </body>
    </html>
  );
}
